# Part 3: Doctors management, menu, dashboard
import os

def append_lines(filepath, lines):
    with open(filepath, "a", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")
    print(f"Appended {len(lines)} lines")

filepath = r"C:\SCRIPTYFY.V02UNSUEÑO\veterinaria_gui_v2.py"

L = []

L.append("")
L.append("    def get_doctores(self):")
L.append("        conn = self.get_db()")
L.append("        rows = conn.execute('SELECT nombre FROM doctores ORDER BY nombre').fetchall()")
L.append("        conn.close()")
L.append("        return [r['nombre'] for r in rows]")
L.append("")
L.append("    def manage_doctores_dialog(self, callback=None):")
L.append("        dialog = tk.Toplevel(self.root)")
L.append("        dialog.title('Gestionar Doctores')")
L.append("        dialog.geometry('360x280')")
L.append("        dialog.resizable(False, False)")
L.append("        dialog.configure(bg='#e8edf2')")
L.append("        dialog.transient(self.root)")
L.append("        dialog.grab_set()")
L.append("        center_dialog(dialog, self.root)")
L.append("")
L.append("        tk.Label(dialog, text='Doctores', font=('Segoe UI', 12, 'bold'),")
L.append("                 bg='#e8edf2', fg='#2c3e50').pack(pady=(12, 5))")
L.append("")
L.append("        lb = tk.Listbox(dialog, font=('Segoe UI', 10), height=8)")
L.append("        lb.pack(fill='both', expand=True, padx=15, pady=5)")
L.append("")
L.append("        def refresh():")
L.append("            lb.delete(0, 'end')")
L.append("            for d in self.get_doctores():")
L.append("                lb.insert('end', d)")
L.append("")
L.append("        refresh()")
L.append("")
L.append("        btn_frame = tk.Frame(dialog, bg='#e8edf2')")
L.append("        btn_frame.pack(fill='x', padx=15, pady=(0, 12))")
L.append("")
L.append("        tk.Button(btn_frame, text='Agregar', bg='#2ecc71', fg='white',")
L.append("                  font=('Segoe UI', 9), relief='flat', padx=12, pady=3,")
L.append("                  cursor='hand2',")
L.append("                  command=lambda: self._add_doctor_dialog(dialog, refresh, callback)")
L.append("                  ).pack(side='left', padx=2)")
L.append("        tk.Button(btn_frame, text='Eliminar', bg='#e74c3c', fg='white',")
L.append("                  font=('Segoe UI', 9), relief='flat', padx=12, pady=3,")
L.append("                  cursor='hand2',")
L.append("                  command=lambda: self._delete_doctor(lb, dialog, refresh, callback)")
L.append("                  ).pack(side='left', padx=2)")
L.append("        tk.Button(btn_frame, text='Cerrar', bg='#95a5a6', fg='white',")
L.append("                  font=('Segoe UI', 9), relief='flat', padx=12, pady=3,")
L.append("                  cursor='hand2', command=dialog.destroy).pack(side='right', padx=2)")
L.append("")
L.append("    def _add_doctor_dialog(self, parent_dialog, refresh_cb, final_cb=None):")
L.append("        d2 = tk.Toplevel(parent_dialog)")
L.append("        d2.title('Nuevo Doctor')")
L.append("        d2.geometry('300x120')")
L.append("        d2.resizable(False, False)")
L.append("        d2.configure(bg='#e8edf2')")
L.append("        d2.transient(parent_dialog)")
L.append("        d2.grab_set()")
L.append("        center_dialog(d2, parent_dialog)")
L.append("        tk.Label(d2, text='Nombre del Doctor:', bg='#e8edf2', font=('Segoe UI', 10)).pack(pady=(15, 5))")
L.append("        e_name = tk.Entry(d2, width=35, font=('Segoe UI', 10))")
L.append("        e_name.pack()")
L.append("        e_name.focus_set()")
L.append("        def save():")
L.append("            name = e_name.get().strip()")
L.append("            if not name:")
L.append("                messagebox.showwarning('Error', 'Ingrese un nombre')")
L.append("                return")
L.append("            conn = self.get_db()")
L.append("            try:")
L.append("                conn.execute('INSERT INTO doctores (nombre) VALUES (?)', (name,))")
L.append("                conn.commit()")
L.append("                conn.close()")
L.append("                d2.destroy()")
L.append("                refresh_cb()")
L.append("                if final_cb:")
L.append("                    final_cb()")
L.append("            except sqlite3.IntegrityError:")
L.append("                conn.close()")
L.append("                messagebox.showwarning('Error', 'Ese doctor ya existe')")
L.append("        add_keyboard_shortcuts(d2, save)")
L.append("        tk.Button(d2, text='Guardar', bg='#2ecc71', fg='white',")
L.append("                  font=('Segoe UI', 10), relief='flat', padx=15, pady=3,")
L.append("                  command=save, cursor='hand2').pack(pady=(10, 5))")
L.append("")
L.append("    def _delete_doctor(self, lb, parent_dialog, refresh_cb, final_cb=None):")
L.append("        sel = lb.curselection()")
L.append("        if not sel:")
L.append("            messagebox.showwarning('Error', 'Seleccione un doctor')")
L.append("            return")
L.append("        name = lb.get(sel[0])")
L.append("        if messagebox.askyesno('Confirmar', f'Eliminar a {name}?'):")
L.append("            conn = self.get_db()")
L.append("            conn.execute('DELETE FROM doctores WHERE nombre=?', (name,))")
L.append("            conn.commit()")
L.append("            conn.close()")
L.append("            refresh_cb()")
L.append("            if final_cb:")
L.append("                final_cb()")
L.append("")
L.append("    def clear_frame(self):")
L.append("        for w in self.root.winfo_children():")
L.append("            if w != self.menu_frame:")
L.append("                w.destroy()")
L.append("")
L.append("    def build_menu(self):")
L.append("        self.menu_frame = tk.Frame(self.root, bg='#2c3e50', height=50)")
L.append("        self.menu_frame.pack(fill='x')")
L.append("        self.menu_frame.pack_propagate(False)")
L.append("        tk.Label(self.menu_frame, text='SCRIPTYFY V.02', font=('Segoe UI', 14, 'bold'),")
L.append("                 bg='#2c3e50', fg='white').pack(side='left', padx=15, pady=10)")
L.append("        buttons = [")
L.append("            ('Inicio', self.show_dashboard),")
L.append("            ('Historial Clinico', self.show_medical_history),")
L.append("            ('Peluqueria/Grooming', self.show_grooming),")
L.append("            ('Productos', self.show_productos),")
L.append("            ('Ventas / Caja', self.show_ventas),")
L.append("        ]")
L.append("        for txt, cmd in buttons:")
L.append("            tk.Button(self.menu_frame, text=txt, font=('Segoe UI', 10),")
L.append("                      bg='#34495e', fg='white', relief='flat', padx=20,")
L.append("                      activebackground='#1abc9c', activeforeground='white',")
L.append("                      command=cmd, cursor='hand2').pack(side='left', padx=2, pady=8)")
L.append("        tk.Button(self.menu_frame, text='Doctores', font=('Segoe UI', 9),")
L.append("                  bg='#3498db', fg='white', relief='flat', padx=10,")
L.append("                  command=lambda: self.manage_doctores_dialog(),")
L.append("                  cursor='hand2').pack(side='right', padx=2)")
L.append("        tk.Button(self.menu_frame, text='+ Due\u00f1o', font=('Segoe UI', 9),")
L.append("                  bg='#e67e22', fg='white', relief='flat', padx=10,")
L.append("                  command=self.add_owner_dialog, cursor='hand2').pack(side='right', padx=2)")
L.append("        tk.Button(self.menu_frame, text='+ Cita', font=('Segoe UI', 9),")
L.append("                  bg='#f39c12', fg='white', relief='flat', padx=10,")
L.append("                  command=self.add_appointment_dialog, cursor='hand2').pack(side='right', padx=2)")
L.append("        tk.Button(self.menu_frame, text='+ Consulta', font=('Segoe UI', 9),")
L.append("                  bg='#1abc9c', fg='white', relief='flat', padx=10,")
L.append("                  command=self.add_medical_record_dialog, cursor='hand2').pack(side='right', padx=2)")
L.append("")
L.append("    def toggle_theme(self):")
L.append("        self._dark_mode = not self._dark_mode")
L.append("        if self._dark_mode:")
L.append("            self._theme_bg = '#2c3e50'")
L.append("            self.root.configure(bg='#2c3e50')")
L.append("        else:")
L.append("            self._theme_bg = '#e8edf2'")
L.append("            self.root.configure(bg='#e8edf2')")
L.append("")
L.append("    # ---------- INICIO ----------")
L.append("    def show_dashboard(self):")
L.append("        self.clear_frame()")
L.append("        main = tk.Frame(self.root, bg='#f0f4f8')")
L.append("        main.pack(fill='both', expand=True, padx=40, pady=30)")
L.append("")
L.append("        logo_path = os.path.join('photos', 'logo.png')")
L.append("        self._dashboard_logo = None")
L.append("        if os.path.exists(logo_path):")
L.append("            pil_img = Image.open(logo_path).resize((100, 100), Image.LANCZOS)")
L.append("            self._dashboard_logo = ImageTk.PhotoImage(pil_img)")
L.append("")
L.append("        header = tk.Frame(main, bg='#f0f4f8')")
L.append("        header.pack(anchor='w', pady=(0, 20))")
L.append("        if self._dashboard_logo:")
L.append("            tk.Label(header, image=self._dashboard_logo, bg='#f0f4f8').pack(side='left', padx=(0, 15))")
L.append("        tk.Label(header, text='Panel Principal', font=('Segoe UI', 16, 'bold'),")
L.append("                 bg='#f0f4f8', fg='#2c3e50').pack(side='left')")
L.append("")
L.append("        conn = self.get_db()")
L.append("        total_d = conn.execute('SELECT COUNT(*) FROM duenos').fetchone()[0]")
L.append("        total_a = conn.execute('SELECT COUNT(*) FROM animales').fetchone()[0]")
L.append("        citas_vet_hoy = conn.execute(")
L.append("            \"SELECT COUNT(*) FROM citas WHERE fecha = ? AND estado = 'pendiente' AND (tipo = 'veterinaria' OR tipo = '')\",")
L.append("            (str(date.today()),)).fetchone()[0]")
L.append("        citas_grooming_hoy = conn.execute(")
L.append("            \"SELECT COUNT(*) FROM citas WHERE fecha = ? AND estado = 'pendiente' AND tipo = 'grooming'\",")
L.append("            (str(date.today()),)).fetchone()[0]")
L.append("        ingresos_hoy = conn.execute(")
L.append("            'SELECT COALESCE(SUM(total), 0) FROM ventas WHERE fecha = ?',")
L.append("            (str(date.today()),)).fetchone()[0]")
L.append("        stock_bajo = conn.execute(")
L.append("            'SELECT COUNT(*) FROM productos WHERE stock <= 3 AND activo = 1').fetchone()[0]")
L.append("")
L.append("        citas_pendientes = conn.execute(")
L.append("            'SELECT c.id, a.nombre as animal, d.nombre as dueno, c.fecha, c.motivo, c.tipo '")
L.append("            'FROM citas c JOIN animales a ON c.id_animal = a.id '")
L.append("            'JOIN duenos d ON c.id_dueno = d.id '")
L.append("            \"WHERE c.estado = 'pendiente' ORDER BY c.fecha ASC\").fetchall()")
L.append("        productos_bajo = conn.execute(")
L.append("            'SELECT nombre, stock FROM productos WHERE stock <= 3 AND activo = 1 ORDER BY stock ASC').fetchall()")
L.append("        conn.close()")
L.append("")
L.append("        cards = tk.Frame(main, bg='#f0f4f8')")
L.append("        cards.pack(fill='x')")
L.append("        for bg_c, val, lab in [('#3498db', total_d, 'Due\u00f1os registrados'),")
L.append("                                ('#2ecc71', total_a, 'Animales registrados'),")
L.append("                                ('#f39c12', citas_vet_hoy, 'Citas Vet Hoy'),")
L.append("                                ('#9b59b6', citas_grooming_hoy, 'Citas Grooming Hoy'),")
L.append("                                ('#1abc9c', f'S/.{ingresos_hoy:.2f}', 'Ingresos Hoy'),")
L.append("                                ('#e74c3c', stock_bajo, 'Stock Bajo')]:")
L.append("            card = tk.Frame(cards, bg='white', highlightbackground='#ddd',")
L.append("                            highlightthickness=1, padx=20, pady=15)")
L.append("            card.pack(side='left', fill='x', expand=True, padx=8)")
L.append("            tk.Label(card, text=str(val), font=('Segoe UI', 36, 'bold'),")
L.append("                     bg='white', fg=bg_c).pack()")
L.append("            tk.Label(card, text=lab, font=('Segoe UI', 10), bg='white', fg='#7f8c8d').pack()")
L.append("")
L.append("        bottom_split = tk.Frame(main, bg='#f0f4f8')")
L.append("        bottom_split.pack(fill='both', expand=True, pady=(15, 0))")
L.append("")
L.append("        left_col = tk.Frame(bottom_split, bg='#f0f4f8')")
L.append("        left_col.pack(side='left', fill='both', expand=True, padx=(0, 8))")

append_lines(filepath, L)
