# Add new methods: grooming, productos, ventas
import os

filepath = r"C:\SCRIPTYFY.V02UNSUEÑO\veterinaria_gui_v2.py"

# Read current file and remove the if __name__ block at the end
with open(filepath, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Find the if __name__ line
if_name_line = None
for i, line in enumerate(lines):
    if 'if __name__ == "__main__":' in line:
        if_name_line = i
        break

if if_name_line is not None:
    # Keep everything up to (but not including) if_name_line
    header_lines = lines[:if_name_line]
    # Save the final block
    footer_lines = lines[if_name_line:]
else:
    header_lines = lines
    footer_lines = ["\nif __name__ == \"__main__\":\n    root = tk.Tk()\n    app = App(root)\n    root.mainloop()\n"]

# Now build the new methods
new_methods = []

new_methods.append("")
new_methods.append("    # ---------- GROOMING / PELUQUERIA ----------")
new_methods.append("    def show_grooming(self):")
new_methods.append("        self.clear_frame()")
new_methods.append("        main = tk.Frame(self.root, bg='#f0f4f8')")
new_methods.append("        main.pack(fill='both', expand=True, padx=20, pady=15)")
new_methods.append("")
new_methods.append("        tk.Label(main, text='Peluqueria / Grooming', font=('Segoe UI', 16, 'bold'),")
new_methods.append("                 bg='#f0f4f8', fg='#2c3e50').pack(anchor='w')")
new_methods.append("")
new_methods.append("        notebook = ttk.Notebook(main)")
new_methods.append("        notebook.pack(fill='both', expand=True, pady=(10, 0))")
new_methods.append("")
new_methods.append("        # Tab 1: Servicios")
new_methods.append("        tab1 = tk.Frame(notebook, bg='#f0f4f8')")
new_methods.append("        notebook.add(tab1, text='Servicios')")
new_methods.append("")
new_methods.append("        top1 = tk.Frame(tab1, bg='#f0f4f8')")
new_methods.append("        top1.pack(fill='x')")
new_methods.append("        tk.Button(top1, text='+ Nuevo Servicio', bg='#2ecc71', fg='white',")
new_methods.append("                  font=('Segoe UI', 9), relief='flat', padx=10, pady=3,")
new_methods.append("                  command=self.add_grooming_service_dialog, cursor='hand2').pack(side='right')")
new_methods.append("")
new_methods.append("        cols_s = ('id', 'nombre', 'descripcion', 'precio', 'duracion', 'tipo')")
new_methods.append("        tree_s = ttk.Treeview(tab1, columns=cols_s, show='headings', height=12)")
new_methods.append("        tree_s.heading('id', text='ID')")
new_methods.append("        tree_s.heading('nombre', text='Nombre')")
new_methods.append("        tree_s.heading('descripcion', text='Descripcion')")
new_methods.append("        tree_s.heading('precio', text='Precio')")
new_methods.append("        tree_s.heading('duracion', text='Duracion (min)')")
new_methods.append("        tree_s.heading('tipo', text='Tipo')")
new_methods.append("        tree_s.column('id', width=40)")
new_methods.append("        tree_s.column('nombre', width=180)")
new_methods.append("        tree_s.column('descripcion', width=250)")
new_methods.append("        tree_s.column('precio', width=70)")
new_methods.append("        tree_s.column('duracion', width=90)")
new_methods.append("        tree_s.column('tipo', width=100)")
new_methods.append("        tree_s.pack(fill='both', expand=True, pady=5)")
new_methods.append("")
new_methods.append("        def load_servicios():")
new_methods.append("            for item in tree_s.get_children():")
new_methods.append("                tree_s.delete(item)")
new_methods.append("            conn = self.get_db()")
new_methods.append("            rows = conn.execute('SELECT * FROM servicios_grooming ORDER BY nombre').fetchall()")
new_methods.append("            conn.close()")
new_methods.append("            for r in rows:")
new_methods.append("                tree_s.insert('', 'end', values=(r['id'], r['nombre'], r['descripcion'],")
new_methods.append("                                               f'S/.{r[\"precio\"]:.2f}', r['duracion_minutos'], r['tipo']))")
new_methods.append("")
new_methods.append("        load_servicios()")
new_methods.append("")
new_methods.append("        def delete_servicio():")
new_methods.append("            sel = tree_s.selection()")
new_methods.append("            if not sel: return")
new_methods.append("            vals = tree_s.item(sel[0], 'values')")
new_methods.append("            if messagebox.askyesno('Confirmar', 'Eliminar servicio?'):")
new_methods.append("                conn = self.get_db()")
new_methods.append("                conn.execute('DELETE FROM servicios_grooming WHERE id=?', (int(vals[0]),))")
new_methods.append("                conn.commit()")
new_methods.append("                conn.close()")
new_methods.append("                load_servicios()")
new_methods.append("")
new_methods.append("        btn_s = tk.Frame(tab1, bg='#f0f4f8')")
new_methods.append("        btn_s.pack(fill='x')")
new_methods.append("        tk.Button(btn_s, text='Eliminar', bg='#e74c3c', fg='white',")
new_methods.append("                  font=('Segoe UI', 9), relief='flat', padx=10, pady=2,")
new_methods.append("                  command=delete_servicio, cursor='hand2').pack(side='left', padx=2)")
new_methods.append("")
new_methods.append("        # Tab 2: Historial Grooming")
new_methods.append("        tab2 = tk.Frame(notebook, bg='#f0f4f8')")
new_methods.append("        notebook.add(tab2, text='Historial Grooming')")
new_methods.append("")
new_methods.append("        cols_h = ('fecha', 'animal', 'servicio', 'precio', 'estilista', 'obs')")
new_methods.append("        tree_h = ttk.Treeview(tab2, columns=cols_h, show='headings', height=12)")
new_methods.append("        tree_h.heading('fecha', text='Fecha')")
new_methods.append("        tree_h.heading('animal', text='Animal')")
new_methods.append("        tree_h.heading('servicio', text='Servicio')")
new_methods.append("        tree_h.heading('precio', text='Precio')")
new_methods.append("        tree_h.heading('estilista', text='Estilista')")
new_methods.append("        tree_h.heading('obs', text='Observaciones')")
new_methods.append("        tree_h.column('fecha', width=90)")
new_methods.append("        tree_h.column('animal', width=150)")
new_methods.append("        tree_h.column('servicio', width=150)")
new_methods.append("        tree_h.column('precio', width=70)")
new_methods.append("        tree_h.column('estilista', width=100)")
new_methods.append("        tree_h.column('obs', width=200)")
new_methods.append("        tree_h.pack(fill='both', expand=True, pady=5)")
new_methods.append("")
new_methods.append("        def load_historial():")
new_methods.append("            for item in tree_h.get_children():")
new_methods.append("                tree_h.delete(item)")
new_methods.append("            conn = self.get_db()")
new_methods.append("            rows = conn.execute(")
new_methods.append("                'SELECT hg.fecha, a.nombre as animal, sg.nombre as servicio, hg.precio, hg.estilista, hg.observaciones '")
new_methods.append("                'FROM historial_grooming hg '")
new_methods.append("                'JOIN animales a ON hg.id_animal = a.id '")
new_methods.append("                'LEFT JOIN servicios_grooming sg ON hg.id_servicio = sg.id '")
new_methods.append("                'ORDER BY hg.fecha DESC').fetchall()")
new_methods.append("            conn.close()")
new_methods.append("            for r in rows:")
new_methods.append("                tree_h.insert('', 'end', values=(")
new_methods.append("                    r['fecha'], r['animal'], r['servicio'] or 'N/A',")
new_methods.append("                    f'S/.{r[\"precio\"]:.2f}', r['estilista'] or '', r['observaciones'] or ''))")
new_methods.append("")
new_methods.append("        load_historial()")
new_methods.append("")
new_methods.append("        # Tab 3: Citas Grooming")
new_methods.append("        tab3 = tk.Frame(notebook, bg='#f0f4f8')")
new_methods.append("        notebook.add(tab3, text='Citas Grooming')")
new_methods.append("")
new_methods.append("        cols_g = ('fecha', 'animal', 'dueno', 'motivo')")
new_methods.append("        tree_g = ttk.Treeview(tab3, columns=cols_g, show='headings', height=12)")
new_methods.append("        tree_g.heading('fecha', text='Fecha')")
new_methods.append("        tree_g.heading('animal', text='Animal')")
new_methods.append("        tree_g.heading('dueno', text='Due\u00f1o')")
new_methods.append("        tree_g.heading('motivo', text='Motivo')")
new_methods.append("        tree_g.column('fecha', width=100)")
new_methods.append("        tree_g.column('animal', width=180)")
new_methods.append("        tree_g.column('dueno', width=180)")
new_methods.append("        tree_g.column('motivo', width=250)")
new_methods.append("        tree_g.pack(fill='both', expand=True, pady=5)")
new_methods.append("")
new_methods.append("        def load_citas_grooming():")
new_methods.append("            for item in tree_g.get_children():")
new_methods.append("                tree_g.delete(item)")
new_methods.append("            conn = self.get_db()")
new_methods.append("            rows = conn.execute(")
new_methods.append("                'SELECT c.fecha, a.nombre as animal, d.nombre as dueno, c.motivo '")
new_methods.append("                'FROM citas c JOIN animales a ON c.id_animal = a.id '")
new_methods.append("                'JOIN duenos d ON c.id_dueno = d.id '")
new_methods.append("                \"WHERE c.tipo = 'grooming' AND c.estado = 'pendiente' ORDER BY c.fecha\").fetchall()")
new_methods.append("            conn.close()")
new_methods.append("            for r in rows:")
new_methods.append("                tree_g.insert('', 'end', values=(r['fecha'], r['animal'], r['dueno'], r['motivo']))")
new_methods.append("")
new_methods.append("        load_citas_grooming()")
new_methods.append("")
new_methods.append("    def add_grooming_service_dialog(self):")
new_methods.append("        dialog = tk.Toplevel(self.root)")
new_methods.append("        dialog.title('Nuevo Servicio de Grooming')")
new_methods.append("        dialog.geometry('400x250')")
new_methods.append("        dialog.resizable(False, False)")
new_methods.append("        dialog.configure(bg='#e8edf2')")
new_methods.append("        dialog.transient(self.root)")
new_methods.append("        dialog.grab_set()")
new_methods.append("        center_dialog(dialog, self.root)")
new_methods.append("")
new_methods.append("        tk.Label(dialog, text='Nombre', bg='#e8edf2', font=('Segoe UI', 10)).grid(row=0, column=0, sticky='e', padx=10, pady=6)")
new_methods.append("        e_nombre = tk.Entry(dialog, width=35, font=('Segoe UI', 10))")
new_methods.append("        e_nombre.grid(row=0, column=1, padx=10, pady=6)")
new_methods.append("        tk.Label(dialog, text='Descripcion', bg='#e8edf2', font=('Segoe UI', 10)).grid(row=1, column=0, sticky='e', padx=10, pady=6)")
new_methods.append("        e_desc = tk.Entry(dialog, width=35, font=('Segoe UI', 10))")
new_methods.append("        e_desc.grid(row=1, column=1, padx=10, pady=6)")
new_methods.append("        tk.Label(dialog, text='Precio', bg='#e8edf2', font=('Segoe UI', 10)).grid(row=2, column=0, sticky='e', padx=10, pady=6)")
new_methods.append("        e_precio = tk.Entry(dialog, width=35, font=('Segoe UI', 10))")
new_methods.append("        e_precio.grid(row=2, column=1, padx=10, pady=6)")
new_methods.append("        tk.Label(dialog, text='Duracion (min)', bg='#e8edf2', font=('Segoe UI', 10)).grid(row=3, column=0, sticky='e', padx=10, pady=6)")
new_methods.append("        e_duracion = tk.Entry(dialog, width=35, font=('Segoe UI', 10))")
new_methods.append("        e_duracion.insert(0, '30')")
new_methods.append("        e_duracion.grid(row=3, column=1, padx=10, pady=6)")
new_methods.append("        tk.Label(dialog, text='Tipo', bg='#e8edf2', font=('Segoe UI', 10)).grid(row=4, column=0, sticky='e', padx=10, pady=6)")
new_methods.append("        e_tipo = ttk.Combobox(dialog, values=['Ba\u00f1o', 'Corte', 'Combo', 'Higiene'], width=32, font=('Segoe UI', 10))")
new_methods.append("        e_tipo.set('Ba\u00f1o')")
new_methods.append("        e_tipo.grid(row=4, column=1, padx=10, pady=6)")
new_methods.append("")
new_methods.append("        def save():")
new_methods.append("            conn = self.get_db()")
new_methods.append("            conn.execute(")
new_methods.append("                'INSERT INTO servicios_grooming (nombre, descripcion, precio, duracion_minutos, tipo) VALUES (?,?,?,?,?)',")
new_methods.append("                (e_nombre.get(), e_desc.get(), float(e_precio.get() or 0), int(e_duracion.get() or 30), e_tipo.get()))")
new_methods.append("            conn.commit()")
new_methods.append("            conn.close()")
new_methods.append("            dialog.destroy()")
new_methods.append("            self.show_grooming()")
new_methods.append("")
new_methods.append("        tk.Button(dialog, text='Guardar', bg='#2ecc71', fg='white',")
new_methods.append("                  font=('Segoe UI', 10), relief='flat', padx=20, pady=5,")
new_methods.append("                  command=save, cursor='hand2').grid(row=5, column=1, pady=15, sticky='e')")
new_methods.append("")
new_methods.append("    def add_grooming_from_detail(self, animal_id, detail_frame, reload_callback):")
new_methods.append("        conn = self.get_db()")
new_methods.append("        servicios = conn.execute('SELECT * FROM servicios_grooming ORDER BY nombre').fetchall()")
new_methods.append("        animal = conn.execute('SELECT nombre FROM animales WHERE id=?', (animal_id,)).fetchone()")
new_methods.append("        conn.close()")
new_methods.append("        if not servicios:")
new_methods.append("            messagebox.showinfo('Info', 'No hay servicios de grooming. Cree uno primero.')")
new_methods.append("            return")
new_methods.append("")
new_methods.append("        dialog = tk.Toplevel(self.root)")
new_methods.append("        dialog.title(f'Registrar Grooming - {animal[\"nombre\"]}')")
new_methods.append("        dialog.geometry('400x250')")
new_methods.append("        dialog.resizable(False, False)")
new_methods.append("        dialog.configure(bg='#e8edf2')")
new_methods.append("        dialog.transient(self.root)")
new_methods.append("        dialog.grab_set()")
new_methods.append("        center_dialog(dialog, self.root)")
new_methods.append("")
new_methods.append("        svc_map = {s['nombre']: s for s in servicios}")
new_methods.append("        tk.Label(dialog, text='Servicio:', bg='#e8edf2', font=('Segoe UI', 10)).grid(row=0, column=0, sticky='e', padx=10, pady=6)")
new_methods.append("        e_servicio = ttk.Combobox(dialog, values=list(svc_map.keys()), width=35, font=('Segoe UI', 10))")
new_methods.append("        e_servicio.set(list(svc_map.keys())[0])")
new_methods.append("        e_servicio.grid(row=0, column=1, padx=10, pady=6)")
new_methods.append("        tk.Label(dialog, text='Precio:', bg='#e8edf2', font=('Segoe UI', 10)).grid(row=1, column=0, sticky='e', padx=10, pady=6)")
new_methods.append("        e_precio = tk.Entry(dialog, width=35, font=('Segoe UI', 10))")
new_methods.append("        e_precio.grid(row=1, column=1, padx=10, pady=6)")
new_methods.append("        tk.Label(dialog, text='Estilista:', bg='#e8edf2', font=('Segoe UI', 10)).grid(row=2, column=0, sticky='e', padx=10, pady=6)")
new_methods.append("        e_estilista = tk.Entry(dialog, width=35, font=('Segoe UI', 10))")
new_methods.append("        e_estilista.grid(row=2, column=1, padx=10, pady=6)")
new_methods.append("        tk.Label(dialog, text='Observaciones:', bg='#e8edf2', font=('Segoe UI', 10)).grid(row=3, column=0, sticky='e', padx=10, pady=6)")
new_methods.append("        e_obs = tk.Entry(dialog, width=35, font=('Segoe UI', 10))")
new_methods.append("        e_obs.grid(row=3, column=1, padx=10, pady=6)")
new_methods.append("")
new_methods.append("        def on_servicio_select(*args):")
new_methods.append("            s = svc_map.get(e_servicio.get())")
new_methods.append("            if s:")
new_methods.append("                e_precio.delete(0, 'end')")
new_methods.append("                e_precio.insert(0, str(s['precio']))")
new_methods.append("        e_servicio.bind('<<ComboboxSelected>>', on_servicio_select)")
new_methods.append("        on_servicio_select()")
new_methods.append("")
new_methods.append("        def save():")
new_methods.append("            conn = self.get_db()")
new_methods.append("            s = svc_map[e_servicio.get()]")
new_methods.append("            conn.execute(")
new_methods.append("                'INSERT INTO historial_grooming (id_animal, id_servicio, fecha, observaciones, precio, estilista) VALUES (?,?,?,?,?,?)',")
new_methods.append("                (animal_id, s['id'], str(date.today()), e_obs.get(), float(e_precio.get() or s['precio']), e_estilista.get()))")
new_methods.append("            conn.commit()")
new_methods.append("            conn.close()")
new_methods.append("            dialog.destroy()")
new_methods.append("            self.show_detail(detail_frame, animal_id, reload_callback)")
new_methods.append("            messagebox.showinfo('Exito', 'Grooming registrado')")
new_methods.append("")
new_methods.append("        tk.Button(dialog, text='Guardar', bg='#2ecc71', fg='white',")
new_methods.append("                  font=('Segoe UI', 10), relief='flat', padx=20, pady=5,")
new_methods.append("                  command=save, cursor='hand2').grid(row=4, column=1, pady=15, sticky='e')")
new_methods.append("")
new_methods.append("    def _seccion_historial_grooming(self, parent, animal_id):")
new_methods.append("        conn = self.get_db()")
new_methods.append("        rows = conn.execute(")
new_methods.append("            'SELECT hg.fecha, sg.nombre as servicio, hg.precio, hg.estilista, hg.observaciones '")
new_methods.append("            'FROM historial_grooming hg '")
new_methods.append("            'LEFT JOIN servicios_grooming sg ON hg.id_servicio = sg.id '")
new_methods.append("            'WHERE hg.id_animal=? ORDER BY hg.fecha DESC', (animal_id,)).fetchall()")
new_methods.append("        conn.close()")
new_methods.append("        if not rows:")
new_methods.append("            return")
new_methods.append("        sec, lbl = self._make_section(parent, 'Historial Grooming', '#9b59b6')")
new_methods.append("        f = self._make_table_frame(parent)")
new_methods.append("        cols = ('gf', 'gs', 'gp', 'ge', 'go')")
new_methods.append("        tree = ttk.Treeview(f, columns=cols, show='headings', height=4)")
new_methods.append("        tree.heading('gf', text='Fecha')")
new_methods.append("        tree.heading('gs', text='Servicio')")
new_methods.append("        tree.heading('gp', text='Precio')")
new_methods.append("        tree.heading('ge', text='Estilista')")
new_methods.append("        tree.heading('go', text='Observaciones')")
new_methods.append("        tree.column('gf', width=90)")
new_methods.append("        tree.column('gs', width=150)")
new_methods.append("        tree.column('gp', width=70)")
new_methods.append("        tree.column('ge', width=100)")
new_methods.append("        tree.column('go', width=180)")
new_methods.append("        tree.pack(fill='x')")
new_methods.append("        for r in rows:")
new_methods.append('            tree.insert("", "end", values=(r["fecha"], r["servicio"] or "N/A",')
new_methods.append('                        f"S/.{r[\'precio\']:.2f}", r["estilista"] or "", r["observaciones"] or ""))')
new_methods.append("")
new_methods.append("    # ---------- PRODUCTOS ----------")
new_methods.append("    def show_productos(self):")
new_methods.append("        self.clear_frame()")
new_methods.append("        main = tk.Frame(self.root, bg='#f0f4f8')")
new_methods.append("        main.pack(fill='both', expand=True, padx=20, pady=15)")
new_methods.append("")
new_methods.append("        top = tk.Frame(main, bg='#f0f4f8')")
new_methods.append("        top.pack(fill='x')")
new_methods.append("        tk.Label(top, text='Productos / Inventario', font=('Segoe UI', 16, 'bold'),")
new_methods.append("                 bg='#f0f4f8', fg='#2c3e50').pack(side='left')")
new_methods.append("        tk.Button(top, text='+ Nuevo Producto', bg='#2ecc71', fg='white',")
new_methods.append("                  font=('Segoe UI', 9), relief='flat', padx=10, pady=3,")
new_methods.append("                  command=lambda: self.add_producto_dialog(self.show_productos), cursor='hand2').pack(side='right')")
new_methods.append("")
new_methods.append("        cols = ('id', 'nombre', 'desc', 'precio_compra', 'precio_venta', 'stock', 'categoria')")
new_methods.append("        tree = ttk.Treeview(main, columns=cols, show='headings', height=18)")
new_methods.append("        tree.heading('id', text='ID')")
new_methods.append("        tree.heading('nombre', text='Nombre')")
new_methods.append("        tree.heading('desc', text='Descripcion')")
new_methods.append("        tree.heading('precio_compra', text='Costo')")
new_methods.append("        tree.heading('precio_venta', text='Venta')")
new_methods.append("        tree.heading('stock', text='Stock')")
new_methods.append("        tree.heading('categoria', text='Categoria')")
new_methods.append("        tree.column('id', width=40)")
new_methods.append("        tree.column('nombre', width=200)")
new_methods.append("        tree.column('desc', width=250)")
new_methods.append("        tree.column('precio_compra', width=70)")
new_methods.append("        tree.column('precio_venta', width=70)")
new_methods.append("        tree.column('stock', width=60)")
new_methods.append("        tree.column('categoria', width=100)")
new_methods.append("        tree.pack(fill='both', expand=True, pady=10)")
new_methods.append("")
new_methods.append("        def load_productos():")
new_methods.append("            for item in tree.get_children():")
new_methods.append("                tree.delete(item)")
new_methods.append("            conn = self.get_db()")
new_methods.append("            rows = conn.execute('SELECT * FROM productos WHERE activo=1 ORDER BY nombre').fetchall()")
new_methods.append("            conn.close()")
new_methods.append("            for r in rows:")
new_methods.append("                item = tree.insert('', 'end', values=(")
new_methods.append("                    r['id'], r['nombre'], r['descripcion'],")
new_methods.append("                    f'S/.{r[\"precio_compra\"]:.2f}', f'S/.{r[\"precio_venta\"]:.2f}',")
new_methods.append("                    r['stock'], r['categoria']))")
new_methods.append("                stock = r['stock']")
new_methods.append("                if stock <= 2:")
new_methods.append("                    tree.tag_configure('critical', background='#fadbd8')")
new_methods.append("                    tree.item(item, tags=('critical',))")
new_methods.append("                elif stock <= 5:")
new_methods.append("                    tree.tag_configure('low', background='#fef9e7')")
new_methods.append("                    tree.item(item, tags=('low',))")
new_methods.append("")
new_methods.append("        load_productos()")
new_methods.append("")
new_methods.append("        btn_frame = tk.Frame(main, bg='#f0f4f8')")
new_methods.append("        btn_frame.pack(fill='x')")
new_methods.append("        tk.Button(btn_frame, text='Editar', bg='#f39c12', fg='white',")
new_methods.append("                  font=('Segoe UI', 9), relief='flat', padx=10, pady=2,")
new_methods.append("                  command=lambda: self.add_producto_dialog(self.show_productos, tree), cursor='hand2').pack(side='left', padx=2)")
new_methods.append("        tk.Button(btn_frame, text='Eliminar', bg='#e74c3c', fg='white',")
new_methods.append("                  font=('Segoe UI', 9), relief='flat', padx=10, pady=2,")
new_methods.append("                  command=lambda: self._delete_producto(tree, load_productos), cursor='hand2').pack(side='left', padx=2)")
new_methods.append("")
new_methods.append("    def _delete_producto(self, tree, reload_cb):")
new_methods.append("        sel = tree.selection()")
new_methods.append("        if not sel: return")
new_methods.append("        vals = tree.item(sel[0], 'values')")
new_methods.append("        if messagebox.askyesno('Confirmar', 'Desactivar producto?'):")
new_methods.append("            conn = self.get_db()")
new_methods.append("            conn.execute('UPDATE productos SET activo=0 WHERE id=?', (int(vals[0]),))")
new_methods.append("            conn.commit()")
new_methods.append("            conn.close()")
new_methods.append("            reload_cb()")
new_methods.append("")
new_methods.append("    def add_producto_dialog(self, callback=None, tree=None):")
new_methods.append("        edit_id = None")
new_methods.append("        if tree:")
new_methods.append("            sel = tree.selection()")
new_methods.append("            if sel:")
new_methods.append("                vals = tree.item(sel[0], 'values')")
new_methods.append("                edit_id = int(vals[0])")
new_methods.append("")
new_methods.append("        dialog = tk.Toplevel(self.root)")
new_methods.append("        title = 'Editar Producto' if edit_id else 'Nuevo Producto'")
new_methods.append("        dialog.title(title)")
new_methods.append("        dialog.geometry('400x300')")
new_methods.append("        dialog.resizable(False, False)")
new_methods.append("        dialog.configure(bg='#e8edf2')")
new_methods.append("        dialog.transient(self.root)")
new_methods.append("        dialog.grab_set()")
new_methods.append("        center_dialog(dialog, self.root)")
new_methods.append("")
new_methods.append("        data = {}")
new_methods.append("        if edit_id:")
new_methods.append("            conn = self.get_db()")
new_methods.append("            d = conn.execute('SELECT * FROM productos WHERE id=?', (edit_id,)).fetchone()")
new_methods.append("            conn.close()")
new_methods.append("            if d:")
new_methods.append("                for k in d.keys(): data[k] = d[k]")
new_methods.append("")
new_methods.append("        fields = [('Nombre', 'nombre'), ('Descripcion', 'descripcion'),")
new_methods.append("                   ('Precio Compra', 'precio_compra'), ('Precio Venta', 'precio_venta'),")
new_methods.append("                   ('Stock', 'stock'), ('Categoria', 'categoria')]")
new_methods.append("        entries = {}")
new_methods.append("        for i, (label, key) in enumerate(fields):")
new_methods.append("            tk.Label(dialog, text=label, bg='#e8edf2', font=('Segoe UI', 10)).grid(")
new_methods.append("                row=i, column=0, sticky='e', padx=10, pady=5)")
new_methods.append("            e = tk.Entry(dialog, width=35, font=('Segoe UI', 10))")
new_methods.append("            if key in data:")
new_methods.append("                e.insert(0, str(data[key]) if data[key] is not None else '')")
new_methods.append("            e.grid(row=i, column=1, padx=10, pady=5)")
new_methods.append("            entries[key] = e")
new_methods.append("")
new_methods.append("        def save():")
new_methods.append("            conn = self.get_db()")
new_methods.append("            if edit_id:")
new_methods.append("                conn.execute(")
new_methods.append("                    'UPDATE productos SET nombre=?, descripcion=?, precio_compra=?, precio_venta=?, stock=?, categoria=? WHERE id=?',")
new_methods.append("                    (entries['nombre'].get(), entries['descripcion'].get(),")
new_methods.append("                     float(entries['precio_compra'].get() or 0), float(entries['precio_venta'].get() or 0),")
new_methods.append("                     int(entries['stock'].get() or 0), entries['categoria'].get(), edit_id))")
new_methods.append("            else:")
new_methods.append("                conn.execute(")
new_methods.append("                    'INSERT INTO productos (nombre, descripcion, precio_compra, precio_venta, stock, categoria) VALUES (?,?,?,?,?,?)',")
new_methods.append("                    (entries['nombre'].get(), entries['descripcion'].get(),")
new_methods.append("                     float(entries['precio_compra'].get() or 0), float(entries['precio_venta'].get() or 0),")
new_methods.append("                     int(entries['stock'].get() or 0), entries['categoria'].get()))")
new_methods.append("            conn.commit()")
new_methods.append("            conn.close()")
new_methods.append("            dialog.destroy()")
new_methods.append("            if callback: callback()")
new_methods.append("")
new_methods.append("        tk.Button(dialog, text='Guardar', bg='#2ecc71', fg='white',")
new_methods.append("                  font=('Segoe UI', 10), relief='flat', padx=20, pady=5,")
new_methods.append("                  command=save, cursor='hand2').grid(row=len(fields), column=1, pady=15, sticky='e')")

# Now write everything
with open(filepath, "w", encoding="utf-8") as f:
    for line in header_lines:
        f.write(line)
    for line in new_methods:
        f.write(line + "\n")
    for line in footer_lines:
        f.write(line)

# Count lines
with open(filepath, "r", encoding="utf-8") as f:
    total_lines = len(f.readlines())

print(f"File written with new methods. Total lines: {total_lines}")
