# Add show_ventas, _add_to_cart, _checkout 
import re

filepath = r"C:\SCRIPTYFY.V02UNSUEÑO\veterinaria_gui_v2.py"

with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

# Find the if __name__ block
footer_marker = '\nif __name__ == "__main__":'

new_methods = []

new_methods.append("")
new_methods.append("    # ---------- VENTAS / CAJA ----------")
new_methods.append("    def show_ventas(self):")
new_methods.append("        self.clear_frame()")
new_methods.append("        main = tk.Frame(self.root, bg='#f0f4f8')")
new_methods.append("        main.pack(fill='both', expand=True, padx=20, pady=15)")
new_methods.append("")
new_methods.append("        tk.Label(main, text='Ventas / Caja', font=('Segoe UI', 16, 'bold'),")
new_methods.append("                 bg='#f0f4f8', fg='#2c3e50').pack(anchor='w')")
new_methods.append("")
new_methods.append("        panes = tk.Frame(main, bg='#f0f4f8')")
new_methods.append("        panes.pack(fill='both', expand=True, pady=(10, 0))")
new_methods.append("")
new_methods.append("        # LEFT: POS / Cart")
new_methods.append("        left = tk.Frame(panes, bg='white', highlightbackground='#ddd', highlightthickness=1)")
new_methods.append("        left.pack(side='left', fill='both', expand=True, padx=(0, 8))")
new_methods.append("")
new_methods.append("        tk.Label(left, text='Punto de Venta', font=('Segoe UI', 12, 'bold'),")
new_methods.append("                 bg='white', fg='#2c3e50', padx=10, pady=8).pack(anchor='w')")
new_methods.append("")
new_methods.append("        # Client selection")
new_methods.append("        client_frame = tk.Frame(left, bg='white', padx=10, pady=5)")
new_methods.append("        client_frame.pack(fill='x')")
new_methods.append("        tk.Label(client_frame, text='Cliente:', bg='white', font=('Segoe UI', 10)).pack(side='left')")
new_methods.append("")
new_methods.append("        def get_client_list():")
new_methods.append("            conn = self.get_db()")
new_methods.append("            rows = conn.execute('SELECT id, nombre, dni FROM duenos ORDER BY nombre').fetchall()")
new_methods.append("            conn.close()")
new_methods.append('            return [f"{r[\"nombre\"]} (DNI: {r[\"dni\"] or \"N/A\"})" for r in rows], {f"{r[\"nombre\"]} (DNI: {r[\"dni\"] or \"N/A\"})": r[\"id\"] for r in rows}')
new_methods.append("")
new_methods.append("        client_list, client_map = get_client_list()")
new_methods.append("        e_cliente = ttk.Combobox(client_frame, values=client_list, width=40, font=('Segoe UI', 10))")
new_methods.append("        e_cliente.pack(side='left', padx=5)")
new_methods.append("")
new_methods.append("        # Product combo + qty")
new_methods.append("        item_frame = tk.Frame(left, bg='white', padx=10, pady=5)")
new_methods.append("        item_frame.pack(fill='x')")
new_methods.append("")
new_methods.append("        def get_product_list():")
new_methods.append("            conn = self.get_db()")
new_methods.append("            rows = conn.execute('SELECT id, nombre, precio_venta, stock FROM productos WHERE activo=1 AND stock>0 ORDER BY nombre').fetchall()")
new_methods.append("            conn.close()")
new_methods.append('            return {f"{r[\"nombre\"]} - S/.{r[\"precio_venta\"]:.2f}": {\"id\": r[\"id\"], \"precio\": r[\"precio_venta\"], \"nombre\": r[\"nombre\"]} for r in rows}')
new_methods.append("")
new_methods.append("        tk.Label(item_frame, text='Producto:', bg='white', font=('Segoe UI', 10)).pack(side='left')")
new_methods.append("        prod_map = get_product_list()")
new_methods.append("        e_producto = ttk.Combobox(item_frame, values=list(prod_map.keys()), width=35, font=('Segoe UI', 10))")
new_methods.append("        e_producto.pack(side='left', padx=5)")
new_methods.append("")
new_methods.append("        tk.Label(item_frame, text='Cant:', bg='white', font=('Segoe UI', 10)).pack(side='left', padx=(5, 2))")
new_methods.append("        e_cant = tk.Spinbox(item_frame, from_=1, to=99, width=5, font=('Segoe UI', 10))")
new_methods.append("        e_cant.pack(side='left')")
new_methods.append("")
new_methods.append("        def add_product_to_cart():")
new_methods.append("            prod_key = e_producto.get()")
new_methods.append("            if not prod_key or prod_key not in prod_map:")
new_methods.append("                messagebox.showwarning('Error', 'Seleccione un producto')")
new_methods.append("                return")
new_methods.append("            p = prod_map[prod_key]")
new_methods.append("            try:")
new_methods.append("                qty = int(e_cant.get())")
new_methods.append("            except:")
new_methods.append("                qty = 1")
new_methods.append("            self._add_to_cart('producto', p['id'], p['nombre'], qty, p['precio'])")
new_methods.append("            update_cart_display()")
new_methods.append("")
new_methods.append("        tk.Button(item_frame, text='Agregar', bg='#3498db', fg='white',")
new_methods.append("                  font=('Segoe UI', 9), relief='flat', padx=8, pady=2,")
new_methods.append("                  command=add_product_to_cart, cursor='hand2').pack(side='left', padx=(5, 0))")
new_methods.append("")
new_methods.append("        # Grooming service in cart")
new_methods.append("        grooming_frame = tk.Frame(left, bg='white', padx=10, pady=5)")
new_methods.append("        grooming_frame.pack(fill='x')")
new_methods.append("")
new_methods.append("        def get_grooming_list():")
new_methods.append("            conn = self.get_db()")
new_methods.append("            rows = conn.execute('SELECT id, nombre, precio FROM servicios_grooming ORDER BY nombre').fetchall()")
new_methods.append("            conn.close()")
new_methods.append('            return {f"{r[\"nombre\"]} - S/.{r[\"precio\"]:.2f}": {\"id\": r[\"id\"], \"precio\": r[\"precio\"], \"nombre\": r[\"nombre\"]} for r in rows}')
new_methods.append("")
new_methods.append("        tk.Label(grooming_frame, text='Grooming:', bg='white', font=('Segoe UI', 10)).pack(side='left')")
new_methods.append("        grooming_map = get_grooming_list()")
new_methods.append("        e_grooming = ttk.Combobox(grooming_frame, values=list(grooming_map.keys()), width=35, font=('Segoe UI', 10))")
new_methods.append("        e_grooming.pack(side='left', padx=5)")
new_methods.append("")
new_methods.append("        def add_grooming_to_cart():")
new_methods.append("            g_key = e_grooming.get()")
new_methods.append("            if not g_key or g_key not in grooming_map:")
new_methods.append("                messagebox.showwarning('Error', 'Seleccione un servicio')")
new_methods.append("                return")
new_methods.append("            g = grooming_map[g_key]")
new_methods.append("            self._add_to_cart('grooming', g['id'], g['nombre'], 1, g['precio'])")
new_methods.append("            update_cart_display()")
new_methods.append("")
new_methods.append("        tk.Button(grooming_frame, text='Agregar', bg='#9b59b6', fg='white',")
new_methods.append("                  font=('Segoe UI', 9), relief='flat', padx=8, pady=2,")
new_methods.append("                  command=add_grooming_to_cart, cursor='hand2').pack(side='left', padx=(5, 0))")
new_methods.append("")
new_methods.append("        # Cart display")
new_methods.append("        cart_frame = tk.Frame(left, bg='white', padx=10, pady=5)")
new_methods.append("        cart_frame.pack(fill='both', expand=True)")
new_methods.append("        tk.Label(cart_frame, text='Carrito:', font=('Segoe UI', 11, 'bold'),")
new_methods.append("                 bg='white', fg='#2c3e50').pack(anchor='w')")
new_methods.append("")
new_methods.append("        cart_cols = ('item', 'qty', 'price', 'subtotal')")
new_methods.append("        cart_tree = ttk.Treeview(cart_frame, columns=cart_cols, show='headings', height=6)")
new_methods.append("        cart_tree.heading('item', text='Item')")
new_methods.append("        cart_tree.heading('qty', text='Cant')")
new_methods.append("        cart_tree.heading('price', text='P.Unit')")
new_methods.append("        cart_tree.heading('subtotal', text='Subtotal')")
new_methods.append("        cart_tree.column('item', width=300)")
new_methods.append("        cart_tree.column('qty', width=50)")
new_methods.append("        cart_tree.column('price', width=80)")
new_methods.append("        cart_tree.column('subtotal', width=80)")
new_methods.append("        cart_tree.pack(fill='both', expand=True)")
new_methods.append("")
new_methods.append("        total_var = tk.StringVar(value='Total: S/.0.00')")
new_methods.append("        tk.Label(cart_frame, textvariable=total_var, font=('Segoe UI', 14, 'bold'),")
new_methods.append("                 bg='white', fg='#e74c3c').pack(anchor='e', pady=(5, 0))")
new_methods.append("")
new_methods.append("        def remove_from_cart():")
new_methods.append("            sel = cart_tree.selection()")
new_methods.append("            if not sel: return")
new_methods.append("            for item in sel:")
new_methods.append("                cart_tree.delete(item)")
new_methods.append("            update_cart_display()")
new_methods.append("")
new_methods.append("        btn_cart = tk.Frame(cart_frame, bg='white')")
new_methods.append("        btn_cart.pack(fill='x', pady=(5, 0))")
new_methods.append("        tk.Button(btn_cart, text='Quitar', bg='#e74c3c', fg='white',")
new_methods.append("                  font=('Segoe UI', 9), relief='flat', padx=10, pady=2,")
new_methods.append("                  command=remove_from_cart, cursor='hand2').pack(side='left', padx=2)")
new_methods.append("        tk.Button(btn_cart, text='Limpiar', bg='#95a5a6', fg='white',")
new_methods.append("                  font=('Segoe UI', 9), relief='flat', padx=10, pady=2,")
new_methods.append("                  command=lambda: ([cart_tree.delete(i) for i in cart_tree.get_children()], update_cart_display()), cursor='hand2').pack(side='left', padx=2)")
new_methods.append("        tk.Button(btn_cart, text='Cobrar', bg='#2ecc71', fg='white',")
new_methods.append("                  font=('Segoe UI', 12, 'bold'), relief='flat', padx=30, pady=5,")
new_methods.append("                  command=self._checkout, cursor='hand2').pack(side='right', padx=2)")
new_methods.append("")
new_methods.append("        # RIGHT: Today sales / history")
new_methods.append("        right = tk.Frame(panes, bg='white', highlightbackground='#ddd', highlightthickness=1)")
new_methods.append("        right.pack(side='left', fill='both', expand=True)")
new_methods.append("")
new_methods.append("        tk.Label(right, text='Ventas de Hoy', font=('Segoe UI', 12, 'bold'),")
new_methods.append("                 bg='white', fg='#2c3e50', padx=10, pady=8).pack(anchor='w')")
new_methods.append("")
new_methods.append("        daily_total_var = tk.StringVar(value='Total Hoy: S/.0.00')")
new_methods.append("        tk.Label(right, textvariable=daily_total_var, font=('Segoe UI', 12, 'bold'),")
new_methods.append("                 bg='white', fg='#1abc9c', padx=10).pack(anchor='w')")
new_methods.append("")
new_methods.append("        venta_cols = ('id', 'fecha', 'cliente', 'total', 'tipo')")
new_methods.append("        venta_tree = ttk.Treeview(right, columns=venta_cols, show='headings', height=15)")
new_methods.append("        venta_tree.heading('id', text='ID')")
new_methods.append("        venta_tree.heading('fecha', text='Fecha')")
new_methods.append("        venta_tree.heading('cliente', text='Cliente')")
new_methods.append("        venta_tree.heading('total', text='Total')")
new_methods.append("        venta_tree.heading('tipo', text='Tipo')")
new_methods.append("        venta_tree.column('id', width=40)")
new_methods.append("        venta_tree.column('fecha', width=90)")
new_methods.append("        venta_tree.column('cliente', width=180)")
new_methods.append("        venta_tree.column('total', width=80)")
new_methods.append("        venta_tree.column('tipo', width=80)")
new_methods.append("        venta_tree.pack(fill='both', expand=True, padx=10, pady=5)")
new_methods.append("")
new_methods.append("        def load_daily_sales():")
new_methods.append("            for item in venta_tree.get_children():")
new_methods.append("                venta_tree.delete(item)")
new_methods.append("            conn = self.get_db()")
new_methods.append("            conn.row_factory = sqlite3.Row")
new_methods.append("            rows = conn.execute(")
new_methods.append("                'SELECT v.id, v.fecha, v.total, v.tipo, COALESCE(d.nombre, \"-\") as cliente '")
new_methods.append("                'FROM ventas v LEFT JOIN duenos d ON v.id_cliente = d.id '")
new_methods.append("                'WHERE v.fecha = ? ORDER BY v.id DESC', (str(date.today()),)).fetchall()")
new_methods.append("            daily_total = conn.execute(")
new_methods.append("                'SELECT COALESCE(SUM(total), 0) FROM ventas WHERE fecha = ?',")
new_methods.append("                (str(date.today()),)).fetchone()[0]")
new_methods.append("            conn.close()")
new_methods.append("            for r in rows:")
new_methods.append('                venta_tree.insert("", "end", values=(r["id"], r["fecha"], r["cliente"],')
new_methods.append('                    f"S/.{r[\'total\']:.2f}", r["tipo"]))')
new_methods.append('            daily_total_var.set(f"Total Hoy: S/.{daily_total:.2f}")')
new_methods.append("")
new_methods.append("        load_daily_sales()")
new_methods.append("")
new_methods.append("        def update_cart_display():")
new_methods.append("            total = 0.0")
new_methods.append("            for item in cart_tree.get_children():")
new_methods.append("                vals = cart_tree.item(item, 'values')")
new_methods.append("                try:")
new_methods.append("                    subtotal_str = vals[3].replace('S/.', '')")
new_methods.append("                    total += float(subtotal_str)")
new_methods.append("                except:")
new_methods.append("                    pass")
new_methods.append('            total_var.set(f"Total: S/.{total:.2f}")')
new_methods.append("")
new_methods.append("        self._cart_items = [")
new_methods.append("        self._cart_tree = cart_tree")
new_methods.append("        self._cart_total_var = total_var")
new_methods.append("        self._cart_update = update_cart_display")
new_methods.append("        self._load_daily_sales = load_daily_sales")
new_methods.append("        self._daily_total_var = daily_total_var")
new_methods.append("        self._venta_tree = venta_tree")
new_methods.append("        self._cart_client = e_cliente")
new_methods.append("        self._cart_client_map = client_map")
new_methods.append("")
new_methods.append("    def _add_to_cart(self, item_type, ref_id, name, qty, price):")
new_methods.append("        subtotal = qty * price")
new_methods.append('        self._cart_tree.insert("", "end", values=(name, qty, f"S/.{price:.2f}", f"S/.{subtotal:.2f}"),')
new_methods.append('            tags=(item_type, str(ref_id)))')
new_methods.append("        self._cart_update()")
new_methods.append("")
new_methods.append("    def _checkout(self):")
new_methods.append("        items = self._cart_tree.get_children()")
new_methods.append("        if not items:")
new_methods.append("            messagebox.showwarning('Carrito vacio', 'Agregue productos al carrito')")
new_methods.append("            return")
new_methods.append("")
new_methods.append("        client_text = self._cart_client.get().strip()")
new_methods.append("        id_cliente = self._cart_client_map.get(client_text) if client_text else None")
new_methods.append("")
new_methods.append("        total = 0.0")
new_methods.append("        cart_data = []")
new_methods.append("        for item in items:")
new_methods.append("            vals = self._cart_tree.item(item, 'values')")
new_methods.append("            tags = self._cart_tree.item(item, 'tags')")
new_methods.append("            item_type = tags[0] if tags else 'producto'")
new_methods.append("            ref_id = int(tags[1]) if len(tags) > 1 else None")
new_methods.append("            qty = int(vals[1])")
new_methods.append("            price_str = vals[2].replace('S/.', '')")
new_methods.append("            subtotal_str = vals[3].replace('S/.', '')")
new_methods.append("            price = float(price_str)")
new_methods.append("            subtotal = float(subtotal_str)")
new_methods.append("            total += subtotal")
new_methods.append("            cart_data.append((item_type, ref_id, vals[0], qty, price, subtotal))")
new_methods.append("")
new_methods.append("        if not messagebox.askyesno('Confirmar Venta', f'Confirmar venta por S/.{total:.2f}?'):")
new_methods.append("            return")
new_methods.append("")
new_methods.append("        conn = self.get_db()")
new_methods.append("        try:")
new_methods.append("            cur = conn.execute(")
new_methods.append("                'INSERT INTO ventas (id_cliente, fecha, total, tipo) VALUES (?, ?, ?, ?)',")
new_methods.append("                (id_cliente, str(date.today()), total, 'mixta'))")
new_methods.append("            venta_id = cur.lastrowid")
new_methods.append("")
new_methods.append("            for item_type, ref_id, name, qty, price, subtotal in cart_data:")
new_methods.append("                conn.execute(")
new_methods.append("                    'INSERT INTO venta_items (id_venta, tipo_item, referencia_id, nombre, cantidad, precio_unitario, subtotal) VALUES (?,?,?,?,?,?,?)',")
new_methods.append("                    (venta_id, item_type, ref_id, name, qty, price, subtotal))")
new_methods.append("                if item_type == 'producto' and ref_id:")
new_methods.append("                    conn.execute('UPDATE productos SET stock = stock - ? WHERE id = ?', (qty, ref_id))")
new_methods.append("")
new_methods.append("            conn.commit()")
new_methods.append("")
new_methods.append("            # Clear cart")
new_methods.append("            for item in items:")
new_methods.append("                self._cart_tree.delete(item)")
new_methods.append("            self._cart_update()")
new_methods.append("            self._load_daily_sales()")
new_methods.append("")
new_methods.append("            messagebox.showinfo('Venta completada', f'Venta S/.{total:.2f} registrada exitosamente')")
new_methods.append("        except Exception as ex:")
new_methods.append("            conn.rollback()")
new_methods.append("            messagebox.showerror('Error', f'Error al procesar venta: {ex}'")
new_methods.append("        finally:")
new_methods.append("            conn.close()")

# Insert new methods before the final block
insert_pos = content.rfind(footer_marker)
if insert_pos == -1:
    # Try to find it without the leading newline
    insert_pos = content.find('if __name__ == "__main__":')
    
if insert_pos >= 0:
    new_content = content[:insert_pos] + "\n" + "\n".join(new_methods) + "\n" + content[insert_pos:]
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(new_content)
    
    with open(filepath, "r", encoding="utf-8") as f:
        total_lines = len(f.readlines())
    print(f"Ventas section added. Total lines: {total_lines}")
else:
    print("ERROR: Could not find if __name__ block")
