# Part 2: App class opening, __init__, _init_tables, init data methods
import os

def append_lines(filepath, lines):
    with open(filepath, "a", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")
    print(f"Appended {len(lines)} lines")

filepath = r"C:\SCRIPTYFY.V02UNSUEÑO\veterinaria_gui_v2.py"

L = []
L.append("")
L.append("class App:")
L.append("    def __init__(self, root):")
L.append("        self.root = root")
L.append("        self.root.title('SCRIPTYFY V.02 - Historial Clinico')")
L.append("        self.root.state('zoomed')")
L.append("        self.root.configure(bg='#e8edf2')")
L.append("        self._dark_mode = False")
L.append("        self._theme_bg = '#e8edf2'")
L.append("        os.makedirs(PHOTOS_DIR, exist_ok=True)")
L.append("        os.makedirs(EXAMENES_DIR, exist_ok=True)")
L.append("        auto_backup_db()")
L.append("        self._init_tables()")
L.append("        self._init_doctores_data()")
L.append("        self._init_productos_default()")
L.append("        self._init_servicios_grooming_default()")
L.append("")
L.append("        style = ttk.Style()")
L.append("        style.theme_use('clam')")
L.append("        style.configure('Treeview', rowheight=28, font=('Segoe UI', 10))")
L.append("        style.configure('Treeview.Heading', font=('Segoe UI', 10, 'bold'))")
L.append("")
L.append("        self.build_menu()")
L.append("        self.show_dashboard()")
L.append("")
L.append("    def get_db(self):")
L.append("        conn = sqlite3.connect(DB_PATH)")
L.append("        conn.row_factory = sqlite3.Row")
L.append("        return conn")
L.append("")
L.append("    def _init_tables(self):")
L.append("        conn = self.get_db()")
L.append("        conn.executescript('''")
L.append("            CREATE TABLE IF NOT EXISTS doctores (id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT UNIQUE);")
L.append("            CREATE TABLE IF NOT EXISTS duenos (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT,")
L.append("                dni TEXT,")
L.append("                nombre TEXT NOT NULL,")
L.append("                telefono TEXT DEFAULT '',")
L.append("                email TEXT DEFAULT '',")
L.append("                direccion TEXT DEFAULT ''")
L.append("            );")
L.append("            CREATE TABLE IF NOT EXISTS animales (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT,")
L.append("                nombre TEXT NOT NULL,")
L.append("                especie TEXT DEFAULT '',")
L.append("                raza TEXT DEFAULT '',")
L.append("                edad INTEGER DEFAULT 0,")
L.append("                peso REAL DEFAULT 0,")
L.append("                sexo TEXT DEFAULT '',")
L.append("                color TEXT DEFAULT '',")
L.append("                fecha_nacimiento TEXT,")
L.append("                esterilizado INTEGER DEFAULT 0,")
L.append("                foto TEXT DEFAULT '',")
L.append("                id_dueno INTEGER NOT NULL,")
L.append("                FOREIGN KEY (id_dueno) REFERENCES duenos(id)")
L.append("            );")
L.append("            CREATE TABLE IF NOT EXISTS citas (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT,")
L.append("                id_animal INTEGER NOT NULL,")
L.append("                id_dueno INTEGER NOT NULL,")
L.append("                fecha TEXT NOT NULL,")
L.append("                motivo TEXT DEFAULT '',")
L.append("                tipo TEXT DEFAULT 'veterinaria',")
L.append("                precio REAL DEFAULT 0,")
L.append("                estado TEXT DEFAULT 'pendiente',")
L.append("                FOREIGN KEY (id_animal) REFERENCES animales(id),")
L.append("                FOREIGN KEY (id_dueno) REFERENCES duenos(id)")
L.append("            );")
L.append("            CREATE TABLE IF NOT EXISTS registros_medicos (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT,")
L.append("                id_animal INTEGER NOT NULL,")
L.append("                fecha TEXT NOT NULL,")
L.append("                hora TEXT,")
L.append("                peso REAL,")
L.append("                doctor TEXT,")
L.append("                diagnostico TEXT,")
L.append("                tratamiento TEXT,")
L.append("                observaciones TEXT,")
L.append("                FOREIGN KEY (id_animal) REFERENCES animales(id));")
L.append("            CREATE TABLE IF NOT EXISTS signos_vitales (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT,")
L.append("                id_registro INTEGER NOT NULL,")
L.append("                temperatura REAL, frecuencia_cardiaca INTEGER,")
L.append("                frecuencia_respiratoria INTEGER, presion_sistolica INTEGER, presion_diastolica INTEGER,")
L.append("                FOREIGN KEY (id_registro) REFERENCES registros_medicos(id));")
L.append("            CREATE TABLE IF NOT EXISTS vacunas (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT, id_animal INTEGER NOT NULL,")
L.append("                tipo TEXT NOT NULL DEFAULT 'vacuna', nombre TEXT NOT NULL, fecha TEXT NOT NULL,")
L.append("                lote TEXT DEFAULT '', dosis TEXT DEFAULT '', proxima_dosis TEXT,")
L.append("                doctor TEXT DEFAULT '', observaciones TEXT DEFAULT '',")
L.append("                FOREIGN KEY (id_animal) REFERENCES animales(id));")
L.append("            CREATE TABLE IF NOT EXISTS alergias (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT, id_animal INTEGER NOT NULL,")
L.append("                alergeno TEXT NOT NULL, tipo TEXT DEFAULT '', severidad TEXT DEFAULT 'leve',")
L.append("                observaciones TEXT DEFAULT '', FOREIGN KEY (id_animal) REFERENCES animales(id));")
L.append("            CREATE TABLE IF NOT EXISTS examenes_auxiliares (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT, id_animal INTEGER NOT NULL,")
L.append("                tipo TEXT NOT NULL, nombre TEXT NOT NULL, fecha TEXT NOT NULL,")
L.append("                archivo TEXT DEFAULT '', resultados TEXT DEFAULT '', observaciones TEXT DEFAULT '',")
L.append("                FOREIGN KEY (id_animal) REFERENCES animales(id));")
L.append("            CREATE TABLE IF NOT EXISTS medicacion (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT, id_animal INTEGER NOT NULL,")
L.append("                medicamento TEXT NOT NULL, dosis TEXT NOT NULL, frecuencia TEXT NOT NULL,")
L.append("                via TEXT DEFAULT '', fecha_inicio TEXT NOT NULL, fecha_fin TEXT,")
L.append("                activo INTEGER DEFAULT 1, observaciones TEXT DEFAULT '',")
L.append("                FOREIGN KEY (id_animal) REFERENCES animales(id));")
L.append("            CREATE TABLE IF NOT EXISTS productos (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT,")
L.append("                nombre TEXT NOT NULL, descripcion TEXT DEFAULT '',")
L.append("                precio_compra REAL NOT NULL DEFAULT 0, precio_venta REAL NOT NULL DEFAULT 0,")
L.append("                stock INTEGER NOT NULL DEFAULT 0, categoria TEXT DEFAULT 'General', activo INTEGER DEFAULT 1")
L.append("            );")
L.append("            CREATE TABLE IF NOT EXISTS servicios_grooming (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT NOT NULL, descripcion TEXT DEFAULT '',")
L.append("                precio REAL NOT NULL DEFAULT 0, duracion_minutos INTEGER DEFAULT 30, tipo TEXT DEFAULT 'Ba\u00f1o'")
L.append("            );")
L.append("            CREATE TABLE IF NOT EXISTS historial_grooming (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT, id_animal INTEGER NOT NULL, id_servicio INTEGER,")
L.append("                fecha TEXT NOT NULL, observaciones TEXT DEFAULT '', precio REAL NOT NULL DEFAULT 0,")
L.append("                estilista TEXT DEFAULT '',")
L.append("                FOREIGN KEY (id_animal) REFERENCES animales(id),")
L.append("                FOREIGN KEY (id_servicio) REFERENCES servicios_grooming(id)")
L.append("            );")
L.append("            CREATE TABLE IF NOT EXISTS ventas (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT, id_cliente INTEGER, id_animal INTEGER,")
L.append("                fecha TEXT NOT NULL, total REAL NOT NULL DEFAULT 0, tipo TEXT DEFAULT 'producto',")
L.append("                estado TEXT DEFAULT 'completada'")
L.append("            );")
L.append("            CREATE TABLE IF NOT EXISTS venta_items (")
L.append("                id INTEGER PRIMARY KEY AUTOINCREMENT, id_venta INTEGER NOT NULL,")
L.append("                tipo_item TEXT NOT NULL, referencia_id INTEGER, nombre TEXT NOT NULL,")
L.append("                cantidad INTEGER NOT NULL DEFAULT 1, precio_unitario REAL NOT NULL, subtotal REAL NOT NULL,")
L.append("                FOREIGN KEY (id_venta) REFERENCES ventas(id)")
L.append("            );")
L.append("        ''')")
L.append("        conn.commit()")
L.append("        try: conn.execute('ALTER TABLE duenos ADD COLUMN dni TEXT'); conn.commit()")
L.append("        except: pass")
L.append("        try: conn.execute(\"ALTER TABLE animales ADD COLUMN sexo TEXT DEFAULT ''\"); conn.commit()")
L.append("        except: pass")
L.append("        try: conn.execute(\"ALTER TABLE animales ADD COLUMN color TEXT DEFAULT ''\"); conn.commit()")
L.append("        except: pass")
L.append("        try: conn.execute('ALTER TABLE animales ADD COLUMN fecha_nacimiento TEXT'); conn.commit()")
L.append("        except: pass")
L.append("        try: conn.execute('ALTER TABLE animales ADD COLUMN esterilizado INTEGER DEFAULT 0'); conn.commit()")
L.append("        except: pass")
L.append("        try: conn.execute(\"ALTER TABLE citas ADD COLUMN tipo TEXT DEFAULT 'veterinaria'\"); conn.commit()")
L.append("        except: pass")
L.append("        try: conn.execute('ALTER TABLE citas ADD COLUMN precio REAL DEFAULT 0'); conn.commit()")
L.append("        except: pass")
L.append("        conn.close()")
L.append("")
L.append("    def _init_doctores_data(self):")
L.append("        conn = self.get_db()")
L.append("        existing = conn.execute('SELECT COUNT(*) FROM doctores').fetchone()[0]")
L.append("        if existing == 0:")
L.append("            for name in ['Carlos Mijica', 'Teresa Buendia']:")
L.append("                conn.execute('INSERT OR IGNORE INTO doctores (nombre) VALUES (?)', (name,))")
L.append("            conn.commit()")
L.append("        conn.close()")
L.append("")
L.append("    def _init_productos_default(self):")
L.append("        conn = self.get_db()")
L.append("        existing = conn.execute('SELECT COUNT(*) FROM productos').fetchone()[0]")
L.append("        if existing == 0:")
L.append("            defaults = [")
L.append("                ('Alimento Premium Perro 15kg', 'Alimento balanceado', 85, 150, 10, 'Alimentos'),")
L.append("                ('Alimento Premium Gato 7kg', 'Alimento balanceado', 60, 110, 10, 'Alimentos'),")
L.append("                ('Antipulgas Frontline', 'Antipulgas', 35, 65, 20, 'Farmacia'),")
L.append("                ('Desparasitante Interno', 'Desparasitante oral', 15, 30, 30, 'Farmacia'),")
L.append("                ('Shampoo Medicado', 'Shampoo dermatologico', 22, 45, 15, 'Higiene'),")
L.append("                ('Collar Isabelino', 'Collar de proteccion', 18, 35, 8, 'Accesorios'),")
L.append("                ('Juguete Pelota', 'Juguete resistente', 10, 22, 25, 'Juguetes'),")
L.append("                ('Cama para Perro M', 'Cama acolchonada', 55, 100, 5, 'Accesorios'),")
L.append("                ('Correa Ajustable', 'Correa de paseo', 12, 28, 20, 'Accesorios'),")
L.append("                ('Plato Doble Acero', 'Plato de acero', 15, 30, 12, 'Accesorios'),")
L.append("            ]")
L.append("            for p in defaults:")
L.append("                conn.execute('INSERT INTO productos (nombre, descripcion, precio_compra, precio_venta, stock, categoria) VALUES (?,?,?,?,?,?)', p)")
L.append("            conn.commit()")
L.append("        conn.close()")
L.append("")
L.append("    def _init_servicios_grooming_default(self):")
L.append("        conn = self.get_db()")
L.append("        existing = conn.execute('SELECT COUNT(*) FROM servicios_grooming').fetchone()[0]")
L.append("        if existing == 0:")
L.append("            defaults = [")
L.append("                ('Ba\u00f1o General', 'Ba\u00f1o con shampoo neutro', 25, 30, 'Ba\u00f1o'),")
L.append("                ('Ba\u00f1o Medicado', 'Ba\u00f1o con shampoo medicado', 35, 40, 'Ba\u00f1o'),")
L.append("                ('Corte Higienico', 'Corte areas sanitarias', 15, 20, 'Corte'),")
L.append("                ('Corte Completo', 'Corte completo segun raza', 45, 60, 'Corte'),")
L.append("                ('Ba\u00f1o + Corte', 'Ba\u00f1o general + corte completo', 55, 75, 'Combo'),")
L.append("                ('Cepillado Dental', 'Limpieza dental', 20, 15, 'Higiene'),")
L.append("                ('Limpieza de Oidos', 'Limpieza y revision', 15, 15, 'Higiene'),")
L.append("                ('Corte de Unas', 'Corte y limado', 10, 10, 'Higiene'),")
L.append("                ('Deslanado', 'Eliminacion pelo muerto', 20, 25, 'Ba\u00f1o'),")
L.append("            ]")
L.append("            for s in defaults:")
L.append("                conn.execute('INSERT INTO servicios_grooming (nombre, descripcion, precio, duracion_minutos, tipo) VALUES (?,?,?,?,?)', s)")
L.append("            conn.commit()")
L.append("        conn.close()")

append_lines(filepath, L)
