# This script generates veterinaria_gui_v2.py
import os

lines = []

# Line 1-8: imports
lines.append("import tkinter as tk")
lines.append("from tkinter import ttk, messagebox, filedialog")
lines.append("import sqlite3")
lines.append("import os")
lines.append("import shutil")
lines.append("import re")
lines.append("from datetime import date, datetime")
lines.append("import json")
lines.append("from PIL import Image, ImageTk")
lines.append("")

# Helper functions
lines.append("")
lines.append("def center_dialog(w, pw):")
lines.append("    w.update_idletasks()")
lines.append("    x = pw.winfo_x() + (pw.winfo_width() - w.winfo_width()) // 2")
lines.append("    y = pw.winfo_y() + (pw.winfo_height() - w.winfo_height()) // 2")
lines.append("    w.geometry('+%d+%d' % (x, y))")
lines.append("")
lines.append("")
lines.append("def add_keyboard_shortcuts(dialog, save_cb):")
lines.append("    dialog.bind('<Escape>', lambda e: dialog.destroy())")
lines.append("    dialog.bind('<Control-Return>', lambda e: save_cb())")
lines.append("")
lines.append("")
lines.append("def validate_required(entries, labels):")
lines.append("    for e, lbl in zip(entries, labels):")
lines.append("        if not e.get().strip():")
lines.append("            messagebox.showerror('Error', f'{lbl} es obligatorio')")
lines.append("            return False")
lines.append("    return True")
lines.append("")
lines.append("")
lines.append("def auto_backup_db():")
lines.append("    backup_dir = os.path.join(os.path.dirname(DB_PATH), 'backups')")
lines.append("    os.makedirs(backup_dir, exist_ok=True)")
lines.append("    today = date.today().isoformat()")
lines.append("    backup_file = os.path.join(backup_dir, f'veterinaria_backup_{today}.db')")
lines.append("    if os.path.exists(backup_file):")
lines.append("        return")
lines.append("    try:")
lines.append("        shutil.copy2(DB_PATH, backup_file)")
lines.append("    except:")
lines.append("        pass")
lines.append("")
lines.append("")

# AutocompleteEntry class
lines.append("class AutocompleteEntry(tk.Frame):")
lines.append("    def __init__(self, master=None, full_values=None, width=37, font=None, **kwargs):")
lines.append("        super().__init__(master, **kwargs)")
lines.append("        self._full_values = full_values or []")
lines.append("        self._selected_value = ''")
lines.append("        self._font = font or ('Segoe UI', 10)")
lines.append("        self._top = None")
lines.append("")
lines.append("        self.entry = tk.Entry(self, width=width, font=self._font)")
lines.append("        self.entry.pack(fill='x')")
lines.append("        self.entry.bind('<KeyRelease>', self._on_keyrelease)")
lines.append("        self.entry.bind('<FocusOut>', self._on_focusout)")
lines.append("")
lines.append("    def get(self):")
lines.append("        return self.entry.get()")
lines.append("")
lines.append("    def set(self, value):")
lines.append("        self.entry.delete(0, 'end')")
lines.append("        self.entry.insert(0, value)")
lines.append("        self._selected_value = value")
lines.append("")
lines.append("    def set_full_values(self, values):")
lines.append("        self._full_values = list(values)")
lines.append("")
lines.append("    def _hide_top(self):")
lines.append("        if self._top:")
lines.append("            self._top.destroy()")
lines.append("            self._top = None")
lines.append("")
lines.append("    def _on_keyrelease(self, event):")
lines.append("        if event.keysym in ('Up', 'Down', 'Return', 'Tab', 'Shift_L', 'Shift_R', 'Control_L', 'Control_R', 'Escape'):")
lines.append("            return")
lines.append("        typed = self.entry.get().lower()")
lines.append("        self._hide_top()")
lines.append("        if not typed:")
lines.append("            matches = list(self._full_values)")
lines.append("        else:")
lines.append("            matches = [v for v in self._full_values if typed in v.lower()]")
lines.append("        if not matches:")
lines.append("            return")
lines.append("        self._top = tk.Toplevel(self.master)")
lines.append("        self._top.wm_overrideredirect(True)")
lines.append("        self._top.wm_geometry('+%d+%d' % (self.winfo_rootx(), self.winfo_rooty() + self.entry.winfo_height()))")
lines.append("        listbox = tk.Listbox(self._top, height=min(len(matches), 6), font=self._font,")
lines.append("                             exportselection=False, activestyle='none')")
lines.append("        listbox.pack(fill='both', expand=True)")
lines.append("        for v in matches:")
lines.append("            listbox.insert('end', v)")
lines.append("")
lines.append("        def on_select(ev=None):")
lines.append("            sel = listbox.curselection()")
lines.append("            if sel:")
lines.append("                val = listbox.get(sel[0])")
lines.append("                self.entry.delete(0, 'end')")
lines.append("                self.entry.insert(0, val)")
lines.append("                self._selected_value = val")
lines.append("            self._hide_top()")
lines.append("            self.entry.focus_set()")
lines.append("")
lines.append("        listbox.bind('<ButtonRelease-1>', on_select)")
lines.append("        listbox.bind('<Return>', on_select)")
lines.append("        self._top.bind('<Escape>', lambda e: self._hide_top())")
lines.append("")
lines.append("    def _on_focusout(self, event):")
lines.append("        self.after(400, self._hide_top)")
lines.append("")
lines.append("")
lines.append("DB_PATH = os.path.join(os.path.dirname(__file__), 'veterinaria.db')")
lines.append("PHOTOS_DIR = os.path.join(os.path.dirname(__file__), 'photos')")
lines.append("EXAMENES_DIR = os.path.join(os.path.dirname(__file__), 'examenes')")
lines.append("")
lines.append("")

# Write to file
output = "\n".join(lines)
with open(r"C:\SCRIPTYFY.V02UNSUEÑO\veterinaria_gui_v2.py", "w", encoding="utf-8") as f:
    f.write(output)
print(f"Part 1 written: {len(lines)} lines")
