# Part 4: Dashboard continuation (citas table, stock bajo, right column, charts, feed)
import os

def append_lines(filepath, lines):
    with open(filepath, "a", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")
    print(f"Appended {len(lines)} lines")

filepath = r"C:\SCRIPTYFY.V02UNSUEÑO\veterinaria_gui_v2.py"

L = []

L.append("")
L.append("        citas_frame = tk.Frame(left_col, bg='#f0f4f8')")
L.append("        citas_frame.pack(fill='x', pady=(0, 10))")
L.append("        tk.Label(citas_frame, text='Citas Pendientes', font=('Segoe UI', 14, 'bold'),")
L.append("                 bg='#f0f4f8', fg='#2c3e50').pack(anchor='w', pady=(0, 10))")
L.append("        if citas_pendientes:")
L.append("            cols = ('fecha', 'animal', 'dueno', 'motivo', 'tipo')")
L.append("            tree = ttk.Treeview(citas_frame, columns=cols, show='headings', height=8)")
L.append("            tree.heading('fecha', text='Fecha')")
L.append("            tree.heading('animal', text='Animal')")
L.append("            tree.heading('dueno', text='Due\u00f1o')")
L.append("            tree.heading('motivo', text='Motivo')")
L.append("            tree.heading('tipo', text='Tipo')")
L.append("            tree.column('fecha', width=90)")
L.append("            tree.column('animal', width=160)")
L.append("            tree.column('dueno', width=160)")
L.append("            tree.column('motivo', width=200)")
L.append("            tree.column('tipo', width=80)")
L.append("            tree.pack(fill='x')")
L.append("            for r in citas_pendientes:")
L.append("                tipo = r['tipo'] or 'veterinaria'")
L.append("                tree.insert('', 'end', values=(r['fecha'], r['animal'], r['dueno'], r['motivo'], tipo))")
L.append("            tree.tag_configure('vet', background='#d6eaf8')")
L.append("            tree.tag_configure('groom', background='#e8daef')")
L.append("            for item in tree.get_children():")
L.append("                vals = tree.item(item, 'values')")
L.append("                if vals[4] == 'grooming':")
L.append("                    tree.item(item, tags=('groom',))")
L.append("                else:")
L.append("                    tree.item(item, tags=('vet',))")
L.append("            def marcar_atendida():")
L.append("                sel = tree.selection()")
L.append("                if not sel: return")
L.append("                vals = tree.item(sel[0], 'values')")
L.append("                c = self.get_db()")
L.append("                c.execute(\"UPDATE citas SET estado='atendida' WHERE fecha=? AND id_animal IN \"")
L.append("                          \"(SELECT id FROM animales WHERE nombre=? AND id_dueno IN \"")
L.append("                          \"(SELECT id FROM duenos WHERE nombre=?))\", (vals[0], vals[1], vals[2]))")
L.append("                c.commit()")
L.append("                c.close()")
L.append("                self.show_dashboard()")
L.append("                messagebox.showinfo('Exito', 'Cita marcada como atendida')")
L.append("            btn_frame = tk.Frame(citas_frame, bg='#e8edf2')")
L.append("            btn_frame.pack(fill='x', pady=(5, 0))")
L.append("            tk.Button(btn_frame, text='Marcar como Atendida', bg='#2ecc71', fg='white',")
L.append("                      font=('Segoe UI', 9), relief='flat', padx=12, pady=3,")
L.append("                      command=marcar_atendida, cursor='hand2').pack(side='left')")
L.append("        else:")
L.append("            tk.Label(citas_frame, text='No hay citas pendientes',")
L.append("                     bg='#f0f4f8', fg='#999', font=('Segoe UI', 10)).pack(anchor='w')")
L.append("")
L.append("        if productos_bajo:")
L.append("            stock_frame = tk.Frame(left_col, bg='#f0f4f8')")
L.append("            stock_frame.pack(fill='x')")
L.append("            tk.Label(stock_frame, text='Stock Bajo', font=('Segoe UI', 12, 'bold'),")
L.append("                     bg='#f0f4f8', fg='#e74c3c').pack(anchor='w', pady=(0, 5))")
L.append("            sf = tk.Frame(stock_frame, bg='white', highlightbackground='#ddd',")
L.append("                          highlightthickness=1, padx=10, pady=5)")
L.append("            sf.pack(fill='x')")
L.append("            for p in productos_bajo:")
L.append("                tk.Label(sf, text=f'  {p[\"nombre\"]} - Stock: {p[\"stock\"]}',")
L.append("                         font=('Segoe UI', 9), bg='white', fg='#e74c3c', anchor='w').pack(fill='x', pady=1)")
L.append("")
L.append("        right_col = tk.Frame(bottom_split, bg='#f0f4f8')")
L.append("        right_col.pack(side='left', fill='both', expand=True)")
L.append("")
L.append("        rec_frame = tk.Frame(right_col, bg='#f0f4f8')")
L.append("        rec_frame.pack(fill='x', pady=(0, 10))")
L.append("        tk.Label(rec_frame, text='Recordatorios', font=('Segoe UI', 14, 'bold'),")
L.append("                 bg='#f0f4f8', fg='#e67e22').pack(anchor='w', pady=(0, 8))")
L.append("        conn_rec = self.get_db()")
L.append("        hoy = date.today()")
L.append("        prox_citas = conn_rec.execute(")
L.append("            'SELECT a.nombre, c.fecha, c.motivo FROM citas c JOIN animales a ON c.id_animal = a.id '")
L.append("            \"WHERE c.fecha BETWEEN ? AND ? AND c.estado='pendiente' ORDER BY c.fecha\",")
L.append("            (hoy.isoformat(), date(hoy.year + (hoy.month + 1 > 12), ((hoy.month + 1) % 12) or 12, 1).isoformat())).fetchall()")
L.append("        vac_pend = conn_rec.execute(")
L.append("            'SELECT v.nombre as vacuna, a.nombre as animal, v.proxima_dosis '")
L.append("            'FROM vacunas v JOIN animales a ON v.id_animal = a.id '")
L.append("            \"WHERE v.proxima_dosis IS NOT NULL AND v.proxima_dosis <= ? ORDER BY v.proxima_dosis\",")
L.append("            (hoy.isoformat(),)).fetchall()")
L.append("        conn_rec.close()")
L.append("        rec_inner = tk.Frame(rec_frame, bg='white', highlightbackground='#ddd',")
L.append("                             highlightthickness=1, padx=10, pady=8)")
L.append("        rec_inner.pack(fill='x')")
L.append("        items_list = []")
L.append("        for r in prox_citas:")
L.append("            items_list.append(f'Proxima cita: {r[\"nombre\"]} - {r[\"fecha\"]} ({r[\"motivo\"]})')")
L.append("        for r in vac_pend:")
L.append("            items_list.append(f'Vacuna pendiente: {r[\"animal\"]} - {r[\"vacuna\"]} (vencida: {r[\"proxima_dosis\"]})')")
L.append("        if items_list:")
L.append("            for txt in items_list:")
L.append("                tk.Label(rec_inner, text='  ' + txt, font=('Segoe UI', 9),")
L.append("                         bg='white', fg='#e67e22', anchor='w').pack(fill='x', pady=1)")
L.append("        else:")
L.append("            tk.Label(rec_inner, text='  No hay recordatorios pendientes',")
L.append("                     font=('Segoe UI', 9), bg='white', fg='#999').pack(anchor='w')")
L.append("")
L.append("        chart_frame = tk.Frame(right_col, bg='white', highlightbackground='#ddd',")
L.append("                               highlightthickness=1)")
L.append("        chart_frame.pack(fill='x', pady=(0, 10))")
L.append("        tk.Label(chart_frame, text='Estadisticas', font=('Segoe UI', 11, 'bold'),")
L.append("                 bg='white', fg='#2c3e50', padx=10, pady=8).pack(anchor='w')")
L.append("        try:")
L.append("            from matplotlib.figure import Figure")
L.append("            from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg")
L.append("            conn_stats = self.get_db()")
L.append("            rows_mes = conn_stats.execute(")
L.append("                \"SELECT strftime('%Y-%m', fecha) as mes, COUNT(*) as total \"")
L.append("                'FROM registros_medicos GROUP BY mes ORDER BY mes').fetchall()")
L.append("            rows_esp = conn_stats.execute(")
L.append("                'SELECT especie, COUNT(*) as total FROM animales GROUP BY especie').fetchall()")
L.append("            rows_doc = conn_stats.execute(")
L.append("                \"SELECT doctor, COUNT(*) as total FROM registros_medicos WHERE doctor IS NOT NULL AND doctor != '' GROUP BY doctor ORDER BY total DESC\").fetchall()")
L.append("            conn_stats.close()")
L.append("")
L.append("            fig = Figure(figsize=(5, 3.5), dpi=85, facecolor='white')")
L.append("")
L.append("            ax1 = fig.add_subplot(221)")
L.append("            if rows_mes:")
L.append("                meses = [r['mes'] for r in rows_mes]")
L.append("                totales = [r['total'] for r in rows_mes]")
L.append("                ax1.bar(meses, totales, color='#3498db', width=0.6)")
L.append("                ax1.set_xticks(range(len(meses)))")
L.append("                ax1.set_xticklabels(meses, rotation=45, fontsize=6)")
L.append("                ax1.set_title('Consultas por Mes', fontsize=9)")
L.append("            else:")
L.append("                ax1.text(0.5, 0.5, 'Sin datos', ha='center', va='center', fontsize=9)")
L.append("                ax1.set_title('Consultas por Mes', fontsize=9)")
L.append("")
L.append("            ax2 = fig.add_subplot(222)")
L.append("            if rows_esp:")
L.append("                labels = [r['especie'] for r in rows_esp]")
L.append("                sizes = [r['total'] for r in rows_esp]")
L.append("                colors_pie = ['#2ecc71', '#3498db', '#e74c3c', '#f39c12', '#9b59b6']")
L.append("                ax2.pie(sizes, labels=labels, autopct='%1.0f%%', colors=colors_pie[:len(sizes)],")
L.append("                        startangle=90, textprops={'fontsize': 8})")
L.append("                ax2.set_title('Pacientes por Especie', fontsize=9)")
L.append("            else:")
L.append("                ax2.text(0.5, 0.5, 'Sin datos', ha='center', va='center', fontsize=9)")
L.append("                ax2.set_title('Pacientes por Especie', fontsize=9)")
L.append("")
L.append("            ax3 = fig.add_subplot(223)")
L.append("            if rows_doc:")
L.append("                docs = [r['doctor'] for r in rows_doc]")
L.append("                counts = [r['total'] for r in rows_doc]")
L.append("                ax3.barh(docs, counts, color='#9b59b6', height=0.5)")
L.append("                ax3.set_xlabel('Consultas', fontsize=8)")
L.append("                ax3.set_title('Consultas por Doctor', fontsize=9)")
L.append("            else:")
L.append("                ax3.text(0.5, 0.5, 'Sin datos', ha='center', va='center', fontsize=9)")
L.append("                ax3.set_title('Consultas por Doctor', fontsize=9)")
L.append("")
L.append("            fig.tight_layout(pad=2)")
L.append("            canvas_chart = FigureCanvasTkAgg(fig, master=chart_frame)")
L.append("            canvas_chart.draw()")
L.append("            canvas_chart.get_tk_widget().pack(fill='x', padx=5, pady=5)")
L.append("        except Exception as ex:")
L.append("            tk.Label(chart_frame, text=f'Grafico no disponible: {ex}', bg='white',")
L.append("                     fg='#999').pack(expand=True)")
L.append("")
L.append("        feed_frame = tk.Frame(right_col, bg='white', highlightbackground='#ddd',")
L.append("                              highlightthickness=1)")
L.append("        feed_frame.pack(fill='x')")
L.append("        tk.Label(feed_frame, text='Actividad Reciente', font=('Segoe UI', 11, 'bold'),")
L.append("                 bg='white', fg='#2c3e50', padx=10, pady=8).pack(anchor='w')")
L.append("        conn3 = self.get_db()")
L.append("        ultimas = conn3.execute(")
L.append("            'SELECT rm.fecha, rm.hora, a.nombre as animal, rm.diagnostico '")
L.append("            'FROM registros_medicos rm JOIN animales a ON rm.id_animal = a.id '")
L.append("            'ORDER BY rm.fecha DESC, rm.hora DESC LIMIT 10').fetchall()")
L.append("        nuevos = conn3.execute(")
L.append("            'SELECT id, nombre, especie, foto FROM animales ORDER BY id DESC LIMIT 5').fetchall()")
L.append("        conn3.close()")
L.append("        feed_inner = tk.Frame(feed_frame, bg='white')")
L.append("        feed_inner.pack(fill='both', expand=True, padx=8, pady=5)")
L.append("        if ultimas:")
L.append("            tk.Label(feed_inner, text='Ultimas Consultas', font=('Segoe UI', 9, 'bold'),")
L.append("                     bg='white', fg='#7f8c8d').pack(anchor='w', pady=(0, 3))")
L.append("            for r in ultimas[:5]:")
L.append("                tk.Label(feed_inner,")
L.append("                    text=f\"{r['fecha']} - {r['animal']}: {r['diagnostico']}\",")
L.append("                    font=('Segoe UI', 9), bg='white', fg='#555',")
L.append("                    anchor='w', wraplength=300, justify='left').pack(fill='x', pady=1)")
L.append("        if nuevos:")
L.append("            tk.Label(feed_inner, text='\\nNuevos Pacientes', font=('Segoe UI', 9, 'bold'),")
L.append("                     bg='white', fg='#7f8c8d').pack(anchor='w', pady=(5, 3))")
L.append("            for r in nuevos:")
L.append("                tk.Label(feed_inner, text=f\"{r['nombre']} ({r['especie']})\",")
L.append("                         font=('Segoe UI', 9), bg='white', fg='#555',")
L.append("                         anchor='w').pack(fill='x', pady=1)")
L.append("")
L.append("        tk.Button(main, text='Ir a Historial Clinico', bg='#1abc9c', fg='white',")
L.append("                  font=('Segoe UI', 12), relief='flat', padx=30, pady=12,")
L.append("                  command=self.show_medical_history, cursor='hand2').pack(pady=40)")

append_lines(filepath, L)
